<?php
// 命名空间，索引到test模块的控制器文件
namespace app\test\controller;

use think\Controller;

class Abc extends Controller {

    public function hello($name){
        return 'hello'.$name;
    }

    // 初始化渲染内容（无论有没有调用都会渲染出来）,必须是继承了Controller
    // 初始化中不能返回，只能用echo来输出
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        echo '<img src="https://www.baidu.com/img/flexible/logo/pc/result.png"  />';
    }


    // 输出数组
    public function arr()
    {
        // 建立数组
        $data = array('a'=>1, 'b'=>2, 'c'=>3);

        // 输出数组，不能直接返回数组，需要转换为json格式
        return json($data);

    }

    // 模板输出，输出的是该模块文件下视图文件中的html文件
    // 控制器名和视图目录下放html文件的对应
    // 方法名和html文件名对应
    public function demo()
    {
        return view();
    }

}

